name: dart_result
version: 0.1.0
description: Result Type for Dart.
repository: https://github.com/veloce/dart_result

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.21.4
